# Generated by Django 5.2.1 on 2025-05-23 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1_object_id", models.PositiveIntegerField()),
                ("player2_object_id", models.PositiveIntegerField()),
                (
                    "player1_symbol",
                    models.CharField(
                        choices=[("❌", "Cross"), ("⭕", "Nought")],
                        max_length=1,
                        verbose_name="player 1 symbol",
                    ),
                ),
                (
                    "player2_symbol",
                    models.CharField(
                        choices=[("❌", "Cross"), ("⭕", "Nought")],
                        max_length=1,
                        verbose_name="player 2 symbol",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player1_content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": (
                                "user_management.user",
                                "user_management.tguser",
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player1_games",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "player2_content_type",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": (
                                "user_management.user",
                                "user_management.tguser",
                            )
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player2_games",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "game",
                "verbose_name_plural": "games",
            },
        ),
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cells",
                    models.CharField(
                        default="         ",
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must contain 9 cells of: X, 0(null), or space",
                                regex="^[\\sX0]{9}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_state",
                        to="tictactoe.game",
                    ),
                ),
                (
                    "parent_state",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_state",
                        to="tictactoe.gamestate",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["player1_object_id"], name="tictactoe_g_player1_cf9796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["player2_object_id"], name="tictactoe_g_player2_4f15c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["created_at"], name="tictactoe_g_created_bcc041_idx"
            ),
        ),
    ]
