# Generated by Django 5.2.1 on 2025-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tictactoe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player1_object_id",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player2_object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
