# Generated by Django 5.2.1 on 2025-06-12 10:08

import django.db.models.deletion
import tictactoe.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tictactoe", "0002_alter_tictactoeproposition_player1_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата прийняття пропозиції (може бути null).",
                null=True,
                verbose_name="accepted at",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата створення пропозиції.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="expires_at",
            field=models.DateTimeField(
                default=tictactoe.models.get_data_expired,
                help_text="Дата закінчення терміну дії пропозиції (може бути null - буде встановлено +7 днів від поточної).",
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Вказує, чи є пропозиція активною.",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player1_content_type",
            field=models.ForeignKey(
                help_text="ContentType об’єкта для гравця 1 (наприклад, TgUser).",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "user_management"), ("model", "user")),
                    models.Q(("app_label", "user_management"), ("model", "tguser")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player1_propositions",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player1_first",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Вказує, чи ходить гравець 1 першим.",
                null=True,
                verbose_name="player1 goes first",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player1_object_id",
            field=models.PositiveBigIntegerField(
                help_text="ID об’єкта гравця 1 (наприклад, Telegram ID)."
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player1_sign",
            field=models.CharField(
                blank=True,
                choices=[("❌", "Cross"), ("⭕", "Nought")],
                default=None,
                help_text='Знак гравця 1 (наприклад, "❌" або "⭕").',
                max_length=1,
                null=True,
                verbose_name="player1 sign",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player2_content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="ContentType для гравця 2 (може бути null).",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "user_management"), ("model", "user")),
                    models.Q(("app_label", "user_management"), ("model", "tguser")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player2_propositions",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player2_object_id",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="ID об’єкта гравця 2 (може бути null).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="player2_sign",
            field=models.CharField(
                blank=True,
                choices=[("❌", "Cross"), ("⭕", "Nought")],
                default=None,
                help_text='Знак гравця 2 (наприклад, "❌" або "⭕").',
                max_length=1,
                null=True,
                verbose_name="player2 sign",
            ),
        ),
        migrations.AlterField(
            model_name="tictactoeproposition",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("incomplete", "Incomplete"),
                    ("completed", "Completed"),
                ],
                default="pending",
                help_text="Статус пропозиції (pending, accepted, declined, incomplete, completed).",
                max_length=20,
                verbose_name="statuses",
            ),
        ),
    ]
