services:
  tlg_front:
    build:
      context: ./tg_front/
      dockerfile: Dockerfile
    env_file:
      - .env.local
    depends_on:
      - db
    command: >
      sh -c "python3 main.py"

  db:
    image: postgres
    env_file:
      - .env.local
    ports:
      - ${POSTGRES_PORT_HOST}:5432
    volumes:
      - db_data:${PGDATA}
volumes:
    db_data:
