# Generated by Django 5.2.1 on 2025-05-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TgStartAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                (
                    "tg_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_attempts",
                        to="user_management.tguser",
                    ),
                ),
            ],
        ),
    ]
