# Generated by Django 5.2.1 on 2025-05-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tguser",
            name="added_to_attachment_menu",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="tguser",
            name="is_premium",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name="TgStartAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                (
                    "tg_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="start_attempts",
                        to="user_management.tguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tg Start Attempt",
                "verbose_name_plural": "Tg Start Attempts",
                "ordering": ["-attempt_time"],
            },
        ),
    ]
